version: "3"

services:
  spicedb:
    container_name: spicedb
    image: "authzed/spicedb"
    command: "serve"
    restart: "always"
    ports:
      - "8080:8080"
      - "9090:9090"
      - "3001:50051"
    environment:
      SPICEDB_GRPC_PRESHARED_KEY: foobar 
      SPICEDB_DATASTORE_ENGINE: memory
